### PR TITLE
Significant changes

### PR DESCRIPTION
**Pull request by maxcabral**
Hi Victor,

I found your library useful for a project I'm building at work. I've extended it to suit my needs and I thought you might appreciate the changes. If not, c'est la vie :).

-Max

### CODE REVIEW

**Comment by victorarias** [comment]
Wow, that's awesome. This should definetely go in! Thanks very much!
I'm assuming that all the tests are passing. I have no way of testing it at the moment, so I'm going to trust you and accept the PR :)
Let me know if you continue to evolve this library - I can give you commit access in that case.

**Comment by maxcabral** [comment]
Yup, tests are passing on my machine using a late version of the SQLite library. I didn't get a chance to get them working on Mono but that seemed to be more of a weird NUnit/Mono issue.

Commit access would be awesome. I have some quick changes I forgot to update the PR with. I can do that via another pull request or push directly if I get access. They're mostly fixes for poor spelling (oops) but do affect interface names (oops again). 

-Max

**Comment by victorarias** [comment]
I just gave you push access to the repo. Consider making the PR anyway for historical reasons. I should review it, but it has been years since I wrote any C# and I don't feel I'm in a position to make constructive comments - I remember the sintax and some parts of the base class library, but I don't really remember how to write idiomatic C# :(

**Comment by maxcabral** [comment]
Sorry for not replying, I've been fairly busy as of late. It looks like that change I was talking about did make it into the PR, so no need for another. Your code was pretty idiomatic as it was. Simple is good afterall :).

**Pull request merged**
